server:
  port: 8080

postgres:
  host: "localhost"
  port: 54320
  username: "postgres"
  password: "secret"
  db-name: "basket"
  connect-timeout: 30s
  connection-lifetime: 30m
  max-open-connections: 10
  max-idle-connections: 5
  debug: true